const startLines = [
    "Every new tab is a fresh start—embrace the possibilities.",
    "Open your mind as you open your browser.",
    "New beginnings start with a single click.",
    "Let curiosity guide you to new discoveries.",
    "Refresh your thoughts, refresh your day.",
    "Step into the unknown—adventure awaits.",
    "Each opening is a chance to learn something new.",
    "Welcome the new, leave the old behind.",
    "Start your journey with an open window.",
    "Opportunities begin where you choose to look.",
    "A new tab, a new perspective.",
    "Open up to inspiration with every click.",
    "Let each window be a gateway to growth.",
    "Begin again—your next idea is just a tab away.",
    "Unlock new thoughts with every fresh start.",
    "Open doors to creativity and wonder.",
    "Let the first page set the tone for your day.",
    "Step forward—every opening is a chance to shine.",
    "Start fresh, think big, explore more.",
    "With every new tab, possibilities unfold.",
    "Open a tab, open your mind to new horizons.",
    "A fresh window brings fresh ideas.",
    "Let each new start spark your imagination.",
    "Every opening is a step toward something greater.",
    "Turn the page—discover what’s next.",
    "New tabs, new dreams, new adventures.",
    "Open to the world, open to growth.",
    "Let the first click inspire your day.",
    "Begin with wonder, continue with purpose.",
    "A new tab is a blank canvas—paint your story.",
    "Change is the beginning of something new.",
    "Embrace new paths, for they lead to growth.",
    "A fresh perspective can transform your day.",
    "Every moment is a chance to start anew.",
    "Let go of the old to welcome the new.",
    "Change refreshes the mind and spirit.",
    "New experiences bring new wisdom.",
    "Transformation starts with a single step.",
    "Renew your thoughts, renew your life.",
    "Change is the key to unlocking potential.",
    "Growth comes from stepping outside your comfort zone.",
    "Every sunrise brings a new opportunity.",
    "Adapting to change opens doors to possibility.",
    "Let your mind wander to discover new ideas.",
    "Change is the art of becoming your best self.",
    "New beginnings are hidden in every ending.",
    "Refresh your outlook, refresh your life.",
    "Change is the bridge to a brighter future.",
    "Embrace uncertainty; it leads to discovery.",
    "Transformation is the heartbeat of progress.",
    "Every change plants the seed of renewal.",
    "Let change inspire your next adventure.",
    "A new chapter begins with a single choice.",
    "Change brings clarity to the mind.",
    "Growth is the reward for embracing change.",
    "Welcome change as a friend, not a foe.",
    "Change is the spark of innovation.",
    "Let new ideas refresh your spirit.",
    "Change is the wind that moves us forward.",
    "Transformation reveals hidden strengths.",
    "Every step toward change is a step toward growth."
];

export default startLines;